my_first_dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: gitpod
      password: postgres
      port: 5432
      dbname: postgres
      schema: testschema
      threads: 1